### PR TITLE
Fix local search only showing liked artists + Question about this fork

### PR DESCRIPTION
**Pull request by Lurux**
Hi !

I fixed a bug where local search would only show favorite artists, here's a PR so we can better centralize the efforts.
It's separated in two commits because I'm a bit dumb and pushed too fast, could probably be squashed together though.

---

Additionally, I wanted to ask you what's your intention with this repo.

As you can see I was preparing to fork the project, but I was made aware of this repo while discussing [here](https://github.com/z-huang/InnerTune/pull/1196#issuecomment-1883463544).

The idea is that (1) I wanted to do a proper fork that could be distributed on F-Droid and installed alongside the original project while we wait for the original author to come back, and (2) I wanted to experiment with ideas that may not align with the original author's anyways.

However, while I have made minor contributions to the app in the past, I don't know a whole bunch about Android development, so it may be a better idea to join forces here if you intend this repo to be more than just a collection of patches to the original app.

Inversely, if you'd prefer to be a contributor to a project not otherwise managed by you, it might be a good idea to let me set up a proper fork, then let everyone know to join forces there.

Hope you have a great day !

### CODE REVIEW

**Comment by BobbyESP** [comment]
Hi Lurux! Sorry for the very late response, didn't saw the PR!!! Sorry so much. Hope that you are nice. Right now I'm quite busy with studies but I have planned to continue with the project as soon as I can. I can give you any permissions you want for the repo if you want to also manage it since I don't have the enough time that I thought I would had.

My intention is also yours. I want to publish the app in F-Droid deleting the PlayStore implementation and go full FOSS.

If you want some more info tell me and we can talk whenever you want!

**Comment by BobbyESP** [comment]
Hi! I have rebased the project, so this PR is now not mergable (before it also wasn't because I have changed a lot of things), so please, if you want create another PR fixing the title error. Thanks!

**Comment by Lurux** [comment]
Hey ! Sorry I've been very busy in the last months so I didn't respond.

It seems @z-huang is in the same case, I don't think the project has been abandoned yet as they clearly warned they would be busy because of their school year, so I don't want to "steal"' their project by making a fork too early.

With that said, it is true there are a lot of improvements that are pending merging in the main project, so I might restart working on this since I'll have more time soon, i have a lot of ideas that I want to explore too.

Initially I wanted to keep my changes based on upstream so they could be easily merged when @z-huang comes back, but I might rebase my repo on yours since I see that it contains a (much needed !) refactoring.

If we decide to go ahead with a (even temporary) fork, I think it would make sense to join forces in a single repo. Where would you prefer to centralize work ? (Here / my repo / make an organisation... ?)

**Comment by BobbyESP** [comment]
Hey there!

No worries at all about the delay, life can get pretty hectic sometimes. It sounds like you and @z-huang have had your hands full lately (also me haha, and I'm still but I think I can keep on working a little bit regurarely).

I completely understand your hesitation about forking the project too soon. It's important to respect the original creators' intentions and give them the space and time they need. However, if there are improvements waiting to be merged and you're itching to dive back in, I'm all for it!

As for where to centralize our efforts, I'm inclined to continue working on my repo for now. We've already built up some traction here with the stars, and it might streamline things to keep the momentum going. Plus, it sounds like you're eyeing some significant refactoring, which could be a valuable addition.

So, if you're up for it, let's collaborate on my repo. I would give you owner permissions. We can combine our ideas and efforts and see where it takes us. Looking forward to you!

**Comment by BobbyESP** [comment]
I have deleted the product flavours for avoiding mistakes at build time, but if we finally merge this into the z-huang repo, we can re-add them.

**Comment by Lurux** [comment]
Ok, sure !

Since it seems like all of us have limited free time, so I think it makes sense to centralize work here - I dunno if @z-huang would be ready to merge a big refactor into their repo without taking a good look at it first, but maybe they'll be happy to join forces here so we're all working on the same repo !

For the time being I'll keep my repo so my existing patches stay easily mergeable upstream, but I'll probably start working on porting them here and making this ready to be shipped if we don't hear from @z-huang by the time we feel there's a strong enough benefit to actually distributing this.

- - -

Do you mind if I set up a discussion forum here like I did in my repo ?

I'm interested with playing with the idea of tracking issues in the discussions forum since it has better categories and it allows us to easily see the most popular issues based on the upvotes, do you think this would make any sense ?

If we decide to distribute this at some point we'll need to come up with a name for it. I used "concerto" in my repo, what do you think about that name ?

- - -

As a side, note, with everything going on with Youtube battling against adblocks and third party apps currently we should expect to have trouble keeping up with API changes.

I dunno how coupled the API code is with the main app code currently, but I think we should be prepared to swap out the API backend if need be - I feel like it might make sense to join forces with the NewPipe extractor and use it as a backend depending how things go - this would also allow us to integrate with more services than just YTM, which seems like a a good idea overall.

**Comment by BobbyESP** [comment]
Thanks for your thoughtful input! It sounds like consolidating our efforts into a central repository could indeed streamline our collaboration. While I'm not entirely sure about @z-huang ’s readiness to merge a large refactor without prior review, pooling our efforts here seems like a promising approach.

Maintaining your repository for the time being to ensure smooth integration of existing patches sounds like a prudent move. And starting the process of porting them over here in parallel is a proactive step.

Setting up a discussion forum similar to what you did in your repo sounds like a great idea. The improved categorization and the ability to highlight popular issues through upvotes could significantly enhance our workflow.

Regarding the name "Concerto," it has a nice ring to it! We could definitely consider it in a short future, but I think that keeping for now the "InnerTune" name is a safe move since the app has like 150k downloads!

Your note about the evolving landscape of YouTube API changes is spot-on. Being prepared to adapt and potentially switch out the backend if necessary seems like a wise strategy. We can also take a look to Piped, that it's basically a YT/YT Music proxy,

Let's keep the dialogue going and continue to refine our approach as we move forward.

**Comment by Lurux** [comment]
Actually it seems like @Malopieds has an active fork with even more activity and features already, maybe we should join forces there ?

@Malopieds what do you think about it ?

**Comment by Malopieds** [comment]
Hi all, I've been looking to both of your repos from afar. I think it is a good idea to unit our forces. I have been trying to update it as much as I could since I had some time lately but I'm still willing to grow more !
I agree that we should keep in mind the fact that the original owner could come back at any time and we should (at least) make things easier for him.

I also agree with the fact that we need a backup plan to YouTube API and either Piped or NewPipe extractor seems to be the way.

I'm looking forward to work with both of you!

**Comment by Lurux** [comment]
Hi @Malopieds, thanks for the input !

Uhm, this is a bit awkward, but I just decided to try your fork, and I think there are very good things in your UI (especially regarding the new homepage), but I think this UI has some major regressions when it comes to the library :confused:

I don't have a lot of time to elaborate rn, but I'm happy to discuss this as soon as I have more time !

Personally I would prefer to start from the original UI, but add the ability to filter by {all / in library / liked} to all possible listings (aka. playlists, artist's songs, album's content, etc), what do you think about this ?

Also I have to say I'm kinda curious why you felt the need to rebuild it in the first place - maybe this would help me understand your decisions ? :thinking:

**Comment by BobbyESP** [comment]
Hi @Malopieds, thanks for joining! 

I've took a look to your fork and seems pretty good! I really love your new player UI, amazing! I saw that you have a lot of work done in there, but now that we have created this would you mind porting some of the changes in here?

I mean, if you guys want to work on my fork because it's "cleaner" (8 commits) is okay, if not we can continue in some of yours.

**Comment by Lurux** [comment]
Considering @Malopieds's fork is already more popular and more advanced, I think it would make more sense to apply your refactoring over there, wouldn't it ? :thinking:

**Comment by BobbyESP** [comment]
> Considering @Malopieds's fork is already more popular and more advanced, I think it would make more sense to apply your refactoring over there, wouldn't it ? 🤔

As you consider! It may be a better option. A lot more work is done and I can port my changes to there.

**Pull request closed without merging**
